### PR TITLE
PP-800 Request denied resource (Naxsi deniedUrl)

### PR DESCRIPTION
**Pull request by rauligs**
## WHAT
- When _Naxsi_ intercepts a request and any non whitelisted rule is being violated, then it makes a POST to the configured **DeniedUrl** parameter (path set in _Naxsi_ see _Related PRs_) to the application receiving the original request (_POST_ with the details of the original request).
- Created the specified resource and logging the _Naxsi_ header containing the causes of the violation.

## WHO
- [X] Developers
- [] WebOps

## Related PRs
https://github.com/alphagov/pay-infra/pull/350

### CODE REVIEW

**Comment by rauligs** [comment]
rebuild

**Comment by rahul-vinayak** [comment]
Is this PR just for PublicAPI, PR doesn't specify so , what about handling it for the Frontend.

**Comment by rauligs** [comment]
_Frontend_ doesn't talk to Public API. There is a different PR for _Frontend_ and is unrelated to each other.

**Comment by rahul-vinayak** [comment]
it doesn't of course, I was just wondering if it was addressed as couldn't see a PR for frontend, but if its covered then its fine.

**Pull request merged**
