### PR TITLE
PP-541 Pass new state structure through from connector

### PR DESCRIPTION
**Pull request by ijmad**
Depends on https://github.com/alphagov/pay-connector/pull/157 and https://github.com/alphagov/pay-endtoend/pull/166

Pass new state structure through from connector filter params to enable search by the new states. As a result, use the new 'finished' boolean to decide whether to return a cancellation link.

Status remains for now, for backwards compatibility reasons. Removed in next PR.

### CODE REVIEW

**Comment by kakumara** [comment]
Few comments in  alphagov/pay-connector#157 which could affect this.  Other than that need this to be green

**Comment by ijmad** [comment]
@kakumara It will only be green once the changes hit connector master

**Comment by ijmad** [comment]
rebuild

**Comment by rauligs** [comment]
rebuild

**Pull request merged**
